### ISSUE TITLE
feature question

### ISSUE THREAD

**Issue by jonesking** [900Seconds/900SecondsSDK#1]
I send the mail to info@livestreamsdk.com

but cant get any reply !
1. Can provide the same function just periscope or meerkat ?
   (i mean We mainly need to use the iOS SDK to stream the camera video up to your platform and use your SDK to play the stream down to one or more clients, this is the first thing we need to try it now.)

2.how many people can upload streaming at same time ? have any restriction ?

3.(when user registered on our platform, we have to create account for the user and allow them to stream their own videos up to your platform)

4.Whether can manage user by our backend server ?

5.charge by app number or broadcast number ?

where the data will be storage ? we need to use AWS , or upload to your cloud ?
transfer data will have extra charge ?

6.can provide record feature ? , let people can see video later

7.what is average delay time from broadcaster to people watch ?

**Comment by IPv6** [comment]
1. Yes, you can. Functionality is quite similar (but our sdk have some unique features like live filtering, etc)
2. There is no restrictions at this time.
3. There is no "users" in common meaning. Streams have author_id, which is just "installation identifier" at this time, without additional logic behind
4.  You can save author_id at your database and query/modify it`s streams via REST API, contact us if you need this. Currently this part of SDK is not open
5. Currently there are no charges, and no plans for this (especially for moderate usage). Video data is stored in AWS (handled completely on our side).
6. Of course, you can always get url for stream, which is normal ".hls" file, playable by any modern player/some browsers
7. Default values are: 8sec for first chunk+network lag to upload chunk on AWS server.
   Default "8 sec" duration can be lowered, but it is not recommended to set it below 2-3 seconds (this is official recommendation by HLS format developers)
