### ISSUE TITLE
Unable to run sample app

### ISSUE THREAD

**Issue by gecoool** [900Seconds/900SecondsSDK#3]
Hello 

I was trying to run the sample app, but apparently using the indicated versions in the pod file, one cannot do that

The error:
[!] Unable to satisfy the following requirements:
- `XMLDictionary (~> 1.4.0)` required by `Podfile`
  (I have also tried adding this manually, upgrade and downgrade versions, for various libraries, but no luck. Further versions of aws, 2.3.3 would not have the symbols required by your libraries and so on:
  Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_BFExecutor", referenced from:
      objc-class-ref in libNine00SecondsSDK.a(DVGStreamsUploadS3Client.o)
  ld: symbol(s) not found for architecture arm64)

However this library exists in repository (pod search reveals just that)
I was wondering if you could upgrade please the 900s sdk to use some valid pairs of libraries, or please advice about how to install/update the pods. Trying to open the provided xcworkspace results in an empty project, so one would normally try to update the pods (which is not possible, with the current pod file)

**Comment by dangerden** [comment]
@gecoool will fix it asap

**Comment by gecoool** [comment]
Hello, thx for the answer !
I am trying to use it in a commercial project, and I could really use any information about how long it would take until the library is upgraded.

**Comment by dangerden** [comment]
@gecoool a couple of days until resolved

**Comment by dangerden** [comment]
@gecoool please check the latest build

**Comment by IPv6** [comment]
Example updated with fixes and new features
