### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by rbarbish** [900Seconds/900SecondsSDK#5]
Undefined symbols for architecture arm64:
"_pipelike_set_eof_callback", referenced from:
l214 in libNine00SecondsSDK.a(libNine00SecondsSDK.a-arm64-master.o)

-Physical Device: iPhone6 - iOS 9.2
-Error also occurs on debugging to simulator (x86)
-Occurs in both sample project and when I attempt to integrate it into my own project

**Comment by CramLabs** [comment]
Could you update this post if you get the sample project to work, I myself am trying to make it work.

**Comment by dangerden** [comment]
@IPv6 could you please have a look?

**Comment by IPv6** [comment]
@rbarbish can you test latest example from SDK? I suspect sdk were intended to be linked against more recent/specific version of ffmpeg. Latest commit contains all the right files, so problem should go away.

If not, we need more information, can you dump linker output from build log panel inside xcode?

**Comment by suu10mac** [comment]
ya @IPv6 it's gets compiled and running now without the "_pipelike_set_eof_callback" error...
