### ISSUE TITLE
From where will get secret key?

### ISSUE THREAD

**Issue by poojab** [900Seconds/900SecondsSDK#9]
Hello,

How to get appid and secret key?
I am not able to register my app on your web console.There is no link which navigate to your registration page, so please provide one.

Regards

**Comment by poojab** [comment]
anyone ?

**Comment by dangerden** [comment]
replied on email

**Comment by basitmashwani** [comment]
@dangerden  i am also unable to get APP id and secret i email on  info@livestreamsdk.com but it bounce back as say email id not found.
